import matplotlib.pyplot as plt
import pandas as pd
from utils.CodeExecuter import CodeExecuter


def matplotlib_run_code(code: str, df: pd.DataFrame) -> None:
    """Run the matplotlib code generated by the API.

    Args:
        code (str): The code to run.
        df (pd.DataFrame): The DataFrame to use.
    """
    imports = {"plt": plt, "df": df}
    CodeExecuter.execute_code(code, imports)
