import io
from contextlib import redirect_stdout


def execute_code(code_string, imports) -> str:
    """Execute the code generated by the API.
    Args:
        code_string (str): The code to execute.
        imports (dict): The imports to use.
    Returns:
        str: The output of the code.
    """
    global_env = {"__builtins__": __builtins__}
    global_env.update(imports)

    with redirect_stdout(io.StringIO()) as output:
        try:
            exec(code_string, imports)
        except Exception as e:
            raise e

    captured_output = output.getvalue()
    lines = code_string.strip().split("\n")
    last_line = lines[-1].strip()

    try:
        return eval(last_line, imports)
    except Exception:
        return captured_output
